<?php

namespace Tests;

use App\Models\Role;
use App\Models\User;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication, RefreshDatabase;

    protected $user;
    protected $admin;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->admin = User::factory(['id' => 1, 'role_id' => Role::IS_ADMIN])->make();
        $this->user = User::factory(['id' => 2, 'role_id' => Role::IS_CLIENT])->make();

        $this->admin->refresh();
        $this->user->refresh();

        self::assertNotNull($this->user);
        self::assertNotNull($this->admin);

    }


}
